// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: st.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace test {

  /// <summary>Holder for reflection information generated from st.proto</summary>
  public static partial class StReflection {

    #region Descriptor
    /// <summary>File descriptor for st.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CghzdC5wcm90byLOAQoCc3QSCQoBYRgBIAEoBRIJCgFiGAIgASgJEhQKBWNo",
            "aWxkGAMgASgLMgUuc3QudBIJCgFjGAQgASgFEgkKAWQYBSABKAgSGwoEZGlj",
            "dBgGIAMoCzINLnN0LkRpY3RFbnRyeRIWCg5hcnJheV9vZl9ieXRlcxgHIAEo",
            "DBokCgF0EgkKAXgYASABKAUSCQoBeRgCIAEoBRIJCgF6GAMgASgFGisKCURp",
            "Y3RFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAU6AjgBQgeqAgR0",
            "ZXN0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::test.st), global::test.st.Parser, new[]{ "A", "B", "Child", "C", "D", "Dict", "ArrayOfBytes" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::test.st.Types.t), global::test.st.Types.t.Parser, new[]{ "X", "Y", "Z" }, null, null, null),
            null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class st : pb::IMessage<st> {
    private static readonly pb::MessageParser<st> _parser = new pb::MessageParser<st>(() => new st());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<st> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::test.StReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public st() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public st(st other) : this() {
      a_ = other.a_;
      b_ = other.b_;
      Child = other.child_ != null ? other.Child.Clone() : null;
      c_ = other.c_;
      d_ = other.d_;
      dict_ = other.dict_.Clone();
      arrayOfBytes_ = other.arrayOfBytes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public st Clone() {
      return new st(this);
    }

    /// <summary>Field number for the "a" field.</summary>
    public const int AFieldNumber = 1;
    private int a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    /// <summary>Field number for the "b" field.</summary>
    public const int BFieldNumber = 2;
    private string b_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string B {
      get { return b_; }
      set {
        b_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "child" field.</summary>
    public const int ChildFieldNumber = 3;
    private global::test.st.Types.t child_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::test.st.Types.t Child {
      get { return child_; }
      set {
        child_ = value;
      }
    }

    /// <summary>Field number for the "c" field.</summary>
    public const int CFieldNumber = 4;
    private int c_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int C {
      get { return c_; }
      set {
        c_ = value;
      }
    }

    /// <summary>Field number for the "d" field.</summary>
    public const int DFieldNumber = 5;
    private bool d_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool D {
      get { return d_; }
      set {
        d_ = value;
      }
    }

    /// <summary>Field number for the "dict" field.</summary>
    public const int DictFieldNumber = 6;
    private static readonly pbc::MapField<string, int>.Codec _map_dict_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForInt32(16), 50);
    private readonly pbc::MapField<string, int> dict_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, int> Dict {
      get { return dict_; }
    }

    /// <summary>Field number for the "array_of_bytes" field.</summary>
    public const int ArrayOfBytesFieldNumber = 7;
    private pb::ByteString arrayOfBytes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ArrayOfBytes {
      get { return arrayOfBytes_; }
      set {
        arrayOfBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as st);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(st other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (A != other.A) return false;
      if (B != other.B) return false;
      if (!object.Equals(Child, other.Child)) return false;
      if (C != other.C) return false;
      if (D != other.D) return false;
      if (!Dict.Equals(other.Dict)) return false;
      if (ArrayOfBytes != other.ArrayOfBytes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (A != 0) hash ^= A.GetHashCode();
      if (B.Length != 0) hash ^= B.GetHashCode();
      if (child_ != null) hash ^= Child.GetHashCode();
      if (C != 0) hash ^= C.GetHashCode();
      if (D != false) hash ^= D.GetHashCode();
      hash ^= Dict.GetHashCode();
      if (ArrayOfBytes.Length != 0) hash ^= ArrayOfBytes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (A != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(A);
      }
      if (B.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(B);
      }
      if (child_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Child);
      }
      if (C != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(C);
      }
      if (D != false) {
        output.WriteRawTag(40);
        output.WriteBool(D);
      }
      dict_.WriteTo(output, _map_dict_codec);
      if (ArrayOfBytes.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(ArrayOfBytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (A != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(A);
      }
      if (B.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(B);
      }
      if (child_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Child);
      }
      if (C != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(C);
      }
      if (D != false) {
        size += 1 + 1;
      }
      size += dict_.CalculateSize(_map_dict_codec);
      if (ArrayOfBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ArrayOfBytes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(st other) {
      if (other == null) {
        return;
      }
      if (other.A != 0) {
        A = other.A;
      }
      if (other.B.Length != 0) {
        B = other.B;
      }
      if (other.child_ != null) {
        if (child_ == null) {
          child_ = new global::test.st.Types.t();
        }
        Child.MergeFrom(other.Child);
      }
      if (other.C != 0) {
        C = other.C;
      }
      if (other.D != false) {
        D = other.D;
      }
      dict_.Add(other.dict_);
      if (other.ArrayOfBytes.Length != 0) {
        ArrayOfBytes = other.ArrayOfBytes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            A = input.ReadInt32();
            break;
          }
          case 18: {
            B = input.ReadString();
            break;
          }
          case 26: {
            if (child_ == null) {
              child_ = new global::test.st.Types.t();
            }
            input.ReadMessage(child_);
            break;
          }
          case 32: {
            C = input.ReadInt32();
            break;
          }
          case 40: {
            D = input.ReadBool();
            break;
          }
          case 50: {
            dict_.AddEntriesFrom(input, _map_dict_codec);
            break;
          }
          case 58: {
            ArrayOfBytes = input.ReadBytes();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the st message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class t : pb::IMessage<t> {
        private static readonly pb::MessageParser<t> _parser = new pb::MessageParser<t>(() => new t());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<t> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::test.st.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public t() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public t(t other) : this() {
          x_ = other.x_;
          y_ = other.y_;
          z_ = other.z_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public t Clone() {
          return new t(this);
        }

        /// <summary>Field number for the "x" field.</summary>
        public const int XFieldNumber = 1;
        private int x_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int X {
          get { return x_; }
          set {
            x_ = value;
          }
        }

        /// <summary>Field number for the "y" field.</summary>
        public const int YFieldNumber = 2;
        private int y_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Y {
          get { return y_; }
          set {
            y_ = value;
          }
        }

        /// <summary>Field number for the "z" field.</summary>
        public const int ZFieldNumber = 3;
        private int z_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Z {
          get { return z_; }
          set {
            z_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as t);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(t other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (X != other.X) return false;
          if (Y != other.Y) return false;
          if (Z != other.Z) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (X != 0) hash ^= X.GetHashCode();
          if (Y != 0) hash ^= Y.GetHashCode();
          if (Z != 0) hash ^= Z.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (X != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(X);
          }
          if (Y != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(Y);
          }
          if (Z != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(Z);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (X != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
          }
          if (Y != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
          }
          if (Z != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Z);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(t other) {
          if (other == null) {
            return;
          }
          if (other.X != 0) {
            X = other.X;
          }
          if (other.Y != 0) {
            Y = other.Y;
          }
          if (other.Z != 0) {
            Z = other.Z;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                X = input.ReadInt32();
                break;
              }
              case 16: {
                Y = input.ReadInt32();
                break;
              }
              case 24: {
                Z = input.ReadInt32();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
