/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: repeated.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "repeated.pb-c.h"
void   inner__init
                     (Inner         *message)
{
  static const Inner init_value = INNER__INIT;
  *message = init_value;
}
size_t inner__get_packed_size
                     (const Inner *message)
{
  assert(message->base.descriptor == &inner__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t inner__pack
                     (const Inner *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &inner__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t inner__pack_to_buffer
                     (const Inner *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &inner__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Inner *
       inner__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Inner *)
     protobuf_c_message_unpack (&inner__descriptor,
                                allocator, len, data);
}
void   inner__free_unpacked
                     (Inner *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &inner__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmessage__init
                     (CMessage         *message)
{
  static const CMessage init_value = CMESSAGE__INIT;
  *message = init_value;
}
size_t cmessage__get_packed_size
                     (const CMessage *message)
{
  assert(message->base.descriptor == &cmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmessage__pack
                     (const CMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmessage__pack_to_buffer
                     (const CMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMessage *
       cmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMessage *)
     protobuf_c_message_unpack (&cmessage__descriptor,
                                allocator, len, data);
}
void   cmessage__free_unpacked
                     (CMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor inner__field_descriptors[2] =
{
  {
    "a",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Inner, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Inner, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned inner__field_indices_by_name[] = {
  0,   /* field[0] = a */
  1,   /* field[1] = b */
};
static const ProtobufCIntRange inner__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor inner__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Inner",
  "Inner",
  "Inner",
  "",
  sizeof(Inner),
  2,
  inner__field_descriptors,
  inner__field_indices_by_name,
  1,  inner__number_ranges,
  (ProtobufCMessageInit) inner__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmessage__field_descriptors[1] =
{
  {
    "c",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CMessage, n_c),
    offsetof(CMessage, c),
    &inner__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmessage__field_indices_by_name[] = {
  0,   /* field[0] = c */
};
static const ProtobufCIntRange cmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMessage",
  "CMessage",
  "CMessage",
  "",
  sizeof(CMessage),
  1,
  cmessage__field_descriptors,
  cmessage__field_indices_by_name,
  1,  cmessage__number_ranges,
  (ProtobufCMessageInit) cmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
